language: node_js
node_js:
  - "node"
  - "4.2"
after_script: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run test-browser-sauce || true'
addons:
  sauce_connect: true
deploy:
  provider: npm
  email: ivan.goncharov.ua@gmail.com
  api_key:
    secure: OjOXs0W+H6Cl5Avi/8gyYL1MklIoiaiOkomx+d+hokENuW31IHZKVYGJN92otqlFmwM27hpOtJ1kjdUSw1ZX6n6yB74INDXVsJ2GBtXpDm2KY/7P9wmW3Qw03nx4i4P/UGtmsh9ie6NF3w3+RZGX6w3CyGA3gafiZnVaiRzIZaeHvkgT5rdrIiWH2+VJOvyKfWNqrKj+BvpEdqvXhr/ZsjBNHlFewU2JeM9iNBR7A24+s+lI9Y2W7JGops6PjnQDidY03pIk+S5fzYFWMsdT+X0cQQBl8EopeubG4R5hZFqPP4OvezKhW3M29Er0AuJkogvxl7KneN12pHw1SPivbkdM/5zNseXwoJ5YvcJPbmMKJnthd8P+c5cOxIAT4KcQ6AemfhhVK8EakJD++l56gtkwRu8QpkcenCRYrKX29C3MWVxfNaLD7IqnU+4gh/PhbLjuIofQUQmNz+aG0bQ1LAItzGzNsit/TOGiKmwO5/dY8EJPiaQMtjzac/zc/zMBDP9P97sozPsP5X+R6TVVutkVAFTk4RXF86qiPYCP322Hq+eMPLT5BgJ7+auJZtEP6+BHHHO7Fyn8kUpMpwzucSoLjoNas516jl1FuRtfMQsohaP1s8x6JI8tLJQ7dkS7hXx58LTKTcA7EZRzmJnQH+UL7LsDgHS7rspAc2byU8U=
  on:
    tags: true
    repo: lucybot/api-spec-converter
